#!/usr/bin/env python3
"""std_doc.py —— std 参考页生成器 v2(ctron-doc JSON 后端;计划 2026-10-09-api-docs-plan.md W1)

真源 = lib/std/*.ct 源码注释(模块头注 + 每个 pub decl 前注释);解析面 =
compiler/ctc.sh doc <file> --format=json(driver_doc.ct iface 投影,T50 S0),
Python 只做渲染。v1 的源码正则路径退役(漏 impl/trait 面、不读注释,且模块
glob 还停在库根布局前的根级 std/,0930 后 glob 落空)。

页形:# std.<mod> / 元行(tier·since,自头注剥出)/ 手写区(<!-- hand:desc -->
界定,再生保留;新页 = 模块头注全文)/ 生成区(pub struct → pub enum →
trait → impl → pub fn;说明列 = 源码注释,缺注 = —)。

用法:
  python3 tools/std_doc.py           # 缺页生成 + 全部生成区刷新(手写区保留)
  python3 tools/std_doc.py --check   # 门禁:重生成与盘上逐字节一致,漂移 rc=1
  python3 tools/std_doc.py --force   # 手写区一并重置为模块头注
"""
import argparse
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
STD = ROOT / "lib" / "std"
OUT = ROOT / "website" / "docs" / "std"
CTC = ROOT / "compiler" / "ctc.sh"

HAND_OPEN = "<!-- hand:desc -->"
HAND_CLOSE = "<!-- /hand:desc -->"
TODO_V1 = "TODO: one-line module description."


def ctron_doc_json(path: pathlib.Path) -> dict:
    """ctc.sh doc --format=json;stdout=JSON、stderr=宿主杂音,必须分离流。
    驱动重拼撞机刷中间态会瞬时假红(E1001),重试一次。"""
    last = ""
    for _ in range(2):
        r = subprocess.run([str(CTC), "doc", str(path), "--format=json"],
                           cwd=ROOT, capture_output=True, text=True)
        if r.returncode == 0:
            try:
                return json.loads(r.stdout)
            except json.JSONDecodeError as e:
                last = f"JSON 解析失败: {e}"
        else:
            last = (r.stdout + r.stderr).strip().splitlines()[-1] if (r.stdout + r.stderr).strip() else f"rc={r.returncode}"
    sys.exit(f"std_doc: ctron-doc 对 {path.name} 两趟皆败: {last}")


def esc(s: str) -> str:
    # 尖括号转义:doc 注释里的 `<…>` 会被 mkdocs 当疑似 HTML 标签(strict 下 INFO、
    # 渲染面吞字);表格单元内不在代码跨度里的说明文本一律字面转义。
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace("|", "\\|").replace("\n", "<br>"))


def split_meta(doc: str):
    """从头注剥 tier/since 行入元行,余下为手写区缺省文本。"""
    tier = since = ""
    body = []
    for ln in doc.splitlines():
        m = re.match(r"^\s*@?\s*tier:\s*(\S+)\s*$", ln)
        if m:
            tier = m.group(1)
            continue
        m = re.match(r"^\s*since:\s*(.+?)\s*$", ln)
        if m:
            since = m.group(1)
            continue
        body.append(ln)
    text = "\n".join(body).strip()
    text = re.sub(rf"^std/\w+\.ct\s*——\s*", "", text)
    return tier, since, text


def fn_sig(it: dict) -> str:
    ps = []
    for p in it.get("params", []):
        if p.get("vaargs"):
            ps.append("...")
        else:
            ps.append(("var " if p.get("mutable") else "") + p["name"] + ": " + p["type"])
    g = "[" + ", ".join(it["generics"]) + "]" if it.get("generics") else ""
    return f"{it['name']}{g}({', '.join(ps)})"


def hand_desc_of(page: pathlib.Path, src_text: str) -> str:
    """手写区缺省:已有页取界定区;v1 旧页迁首段(TODO 占位则弃);新页 = 模块头注。"""
    if page.exists():
        t = page.read_text()
        if HAND_OPEN in t and HAND_CLOSE in t:
            return t.split(HAND_OPEN, 1)[1].split(HAND_CLOSE, 1)[0].strip("\n")
        m = re.search(r"# std\.\w+\s*\n\n(.*?)\n\n## ", t, re.S)
        if m and m.group(1).strip() != TODO_V1:
            return m.group(1).strip()
    return src_text


def render(mod: str, data: dict, hand: str) -> str:
    tier, since, src_text = split_meta(data.get("doc", ""))
    meta = " · ".join(f"`{k}: {v}`" for k, v in (("tier", tier), ("since", since)) if v)
    out = [
        f"<!-- generated by tools/std_doc.py v2 from lib/std/{mod}.ct (ctron-doc iface); regenerate refreshes all but the hand region -->\n",
        f"# std.{mod}\n",
    ]
    if meta:
        out.append(f"\n{meta}\n")
    if not hand:
        hand = "(待补:模块简介——回 lib/std/%s.ct 头注或在此手写)" % mod
    out.append(f"\n{HAND_OPEN}\n{hand}\n{HAND_CLOSE}\n")

    iface = data.get("iface", [])
    structs = [i for i in iface if i["kind"] == "struct"]
    enums = [i for i in iface if i["kind"] == "enum"]
    traits = [i for i in iface if i["kind"] == "trait"]
    impls = [i for i in iface if i["kind"] == "impl"]
    fns = [i for i in iface if i["kind"] == "fn"]

    if structs:
        out.append("\n## pub struct\n")
        for s in structs:
            g = "[" + ", ".join(s["generics"]) + "]" if s.get("generics") else ""
            out.append(f"\n**struct {s['name']}{g}**\n")
            if s.get("doc"):
                out.append(f"\n{esc(s['doc'])}\n")
            out.append("\n| Field | Type |\n|---|---|\n")
            for f in s.get("fields", []):
                name = ("var " if f.get("mutable") else "") + f["name"]
                out.append(f"| `{name}` | `{f['type']}` |\n")
    if enums:
        out.append("\n## pub enum\n")
        for e in enums:
            g = "[" + ", ".join(e["generics"]) + "]" if e.get("generics") else ""
            out.append(f"\n**enum {e['name']}{g}**\n")
            if e.get("doc"):
                out.append(f"\n{esc(e['doc'])}\n")
            out.append("\n| Variant | Payload |\n|---|---|\n")
            for v in e.get("variants", []):
                if v.get("tuple") is not None:
                    pay = "(" + ", ".join(v["tuple"]) + ")"
                elif v.get("fields") is not None:
                    pay = "{ " + ", ".join(("var " if f.get("mutable") else "") + f["name"] + ": " + f["type"] for f in v["fields"]) + " }"
                else:
                    pay = ""
                out.append(f"| `{v['name']}` | `{pay}` |\n" if pay else f"| `{v['name']}` | — |\n")
    if traits:
        out.append("\n## trait\n")
        for t in traits:
            out.append(f"\n**trait {t['name']}**\n")
            if t.get("doc"):
                out.append(f"\n{esc(t['doc'])}\n")
            out.append("\n```ct\n" + "\n".join(t.get("sigs", [])) + "\n```\n")
    if impls:
        out.append("\n## impl\n")
        for i in impls:
            sig = i.get("sig", "")
            out.append(f"\n```ct\n{sig}" + ("\n" + "\n".join("    " + s for s in i.get("sigs", [])) if i.get("sigs") else "") + "\n```\n")
    if fns:
        out.append("\n## pub fn\n")
        out.append("\n| Signature | Returns | Description |\n|---|---|---|\n")
        for f in fns:
            ret = f.get("ret", "")
            desc = esc(f["doc"]) if f.get("doc") else "—"
            out.append(f"| `{fn_sig(f)}` | `{ret}` | {desc} |\n")
    out.append("\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate std reference pages via ctron-doc JSON backend.")
    ap.add_argument("--check", action="store_true", help="drift gate: rendered pages must equal on-disk bytes")
    ap.add_argument("--force", action="store_true", help="also reset hand regions to module doc comments")
    ns = ap.parse_args()

    mods = sorted(p.stem for p in STD.glob("*.ct"))
    if not mods:
        sys.exit(f"std_doc: {STD} 无模块,glob 落空")

    index = [
        "# Std Reference\n\n",
        "Signature tables and per-item descriptions are generated by "
        "[tools/std_doc.py](https://github.com/ZturnLibs/Ctron/blob/main/tools/std_doc.py) "
        "from `lib/std/*.ct` source doc comments (ctron-doc iface projection). "
        "Module description sections between the `hand:desc` markers are hand-written.\n\n",
        "> Agent channel: `compiler/ctc.sh doc lib/std/<mod>.ct --format=json` "
        "(pub symbol table with doc comments, deterministic).\n\n",
        "> Chinese translations of the Std Reference are pending; descriptions follow "
        "source comments (mostly Chinese) for now.\n\n",
        "| Module | Page |\n|---|---|\n",
    ]

    drift = []
    for mod in mods:
        data = ctron_doc_json(STD / f"{mod}.ct")
        page = OUT / f"{mod}.md"
        src_text = split_meta(data.get("doc", ""))[2]
        hand = src_text if ns.force else hand_desc_of(page, src_text)
        rendered = render(mod, data, hand)
        if ns.check:
            if not page.exists() or page.read_text() != rendered:
                drift.append(mod)
        else:
            page.write_text(rendered)
        index.append(f"| std.{mod} | [{mod}.md]({mod}.md) |\n")

    idx = OUT / "README.md"
    if ns.check:
        if not idx.exists() or idx.read_text() != "".join(index):
            drift.append("README.md(index)")
        if drift:
            print("std_doc --check: 漂移 " + " ".join(drift) + " —— 复跑 python3 tools/std_doc.py 后随批提交")
            return 1
        print(f"std_doc --check: {len(mods)} 页 + index 逐字节一致")
        return 0

    idx.write_text("".join(index))
    print(f"std_doc: {len(mods)} 模块页 + index -> {OUT}(生成区已刷新;手写区保留{';--force 已重置' if ns.force else ''})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
