#!/usr/bin/env python3
"""std_doc.py —— 从 std/*.ct 扫 pub fn 签名生成 website/docs/std/ 参考页(骨架,人补说明)。

用法:
  python3 tools/std_doc.py           # 缺页生成、已有页保留(preserve);索引 README.md 总是刷新
  python3 tools/std_doc.py --force   # 强制覆盖全部模块页(手写说明会丢)
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "website" / "docs" / "std"

# 签名逐行匹配,行尾 K&R 左花括号(`\{$` 收尾,不用 `\{\s*$`——\s 会吞换行跨行)。
# 形参用贪婪 (.*) 捕获:闭包型形参含嵌套括号(如 `cmp: fn(T, T) -> I32`),
# 任务书原 regex 的 [^)]* 会在第一个 `)` 处截断、返回类型错乱,故放宽。
# fn 名与 `(` 之间可有泛型参表 `[V]`/`[K: Eq, V]`,原 regex 漏掉全部泛型 fn,故补 (?:\[[^\]]*\])?。
SIG = re.compile(r"^pub fn (\w+)(?:\[[^\]]*\])?\((.*)\)\s*(?:->\s*(.+?))?\s*\{$", re.MULTILINE)


def render(mod: str, source: str) -> str:
    rows = []
    for m in SIG.finditer(source):
        name, args, ret = m.group(1), m.group(2).strip(), (m.group(3) or "Unit").strip()
        rows.append(f"| `{name}({args})` | `{ret}` | TODO |")
    body = "\n".join(rows) or "| — | — | no pub fn in this module yet |"
    return (
        f"<!-- Generated by tools/std_doc.py from std/{mod}.ct. -->\n"
        f"<!-- Skeleton: hand-write the module description below; regenerating preserves this page unless --force. -->\n"
        f"# std.{mod}\n\nTODO: one-line module description.\n\n"
        f"## pub fn\n\n| Signature | Returns | Description |\n|---|---|---|\n{body}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate std reference pages from std/*.ct pub fn signatures.")
    ap.add_argument("--force", action="store_true",
                    help="overwrite existing module pages (default: preserve hand-edited pages)")
    ns = ap.parse_args()

    mods = sorted(p.stem for p in (ROOT / "std").glob("*.ct"))  # std/gui/ 子目录天然不在 glob 内
    OUT.mkdir(parents=True, exist_ok=True)

    index = [
        "# Std Reference\n\n",
        "Standard library reference. Signature tables are generated by "
        "[tools/std_doc.py](https://github.com/Zturn/Ctron/blob/main/tools/std_doc.py) "
        "from `std/*.ct`; module descriptions are hand-written.\n\n"
        "> Chinese translations of the Std Reference are pending; it is English-only for now.\n\n",
        "| Module | Page |\n|---|---|\n",
    ]
    generated = preserved = sigs = 0
    for mod in mods:
        source = (ROOT / "std" / f"{mod}.ct").read_text()
        sigs += len(SIG.findall(source))
        page = OUT / f"{mod}.md"
        if page.exists() and not ns.force:
            preserved += 1  # preserve 缺省:手写说明不丢
        else:
            page.write_text(render(mod, source))
            generated += 1
        index.append(f"| std.{mod} | [{mod}.md]({mod}.md) |\n")
    (OUT / "README.md").write_text("".join(index))
    print(f"std_doc: {len(mods)} modules, {sigs} signatures -> {OUT} "
          f"({generated} generated, {preserved} preserved, index refreshed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
